name: ezmlm FreeBSD

on:
  push:
    paths:
      - '**/ezmlm-x/**'
      - .github/workflows/ezmlm-freebsd.yml
      - '!**/ezmlm-x/debian/*'
      - '!**/ezmlm-x/ezmlm.spec.in'
      - '!**/doc/*'
      - '!**.md'
      - '!**/ezmlm-c-cpp.yml'
      - '!**/ezmlm-obs.yml'

jobs:
  testfreebsd:
    runs-on: macos-latest
    name: FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v2
      with:
        path: main
    - uses: actions/checkout@v2
      with:
        repository: mbhangui/libqmail
        path: libqmail
    - name: build ezmlm
      id: FreeBSD
      uses: vmactions/freebsd-vm@v0.1.2
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: pkg install -y curl automake autoconf libtool pkgconf
        run: |
          cd libqmail; ./default.configure; make; make install-strip
          cd ../main/ezmlm-x
          ./default.configure
          make
