name: ezmlmn obs trigger

on:
  push:
    paths:
      - '**/ezmlmn-x/**'
      - '**/prepare_obs'
      - '**/catChangeLog'
      - .github/workflows/ezmlmn-obs.yml
      - '!**/doc/*'
      - '!**.md'
      - '!**/ezmlmn-freebsd.yml'
      - '!**/ezmlmn-c-cpp.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout_ezmlmn
      uses: actions/checkout@v2
    - name: checkout_qmail
      uses: actions/checkout@v2
      with:
        repository: mbhangui/libqmail
        path: libqmail

    - name: install_qmail
      run: |
        sudo apt-get update; sudo apt-get install libssl-dev libmysqlclient-dev
        cd libqmail; ./default.configure; make; sudo make install-strip
    - name: prepare obs
      run: cd ezmlmn-x; ./prepare_obs ezmlmn
    - uses: actions/upload-artifact@v2
      with:
        name: ezmlmn
        path: ~/stage
    - shell: bash
      name: trigger_obs
      run: |
        # create ssh environment
        mkdir ~/.ssh
        echo "${{secrets.sf_private_key}}" > ~/.private_key
        chmod 600 ~/.private_key
        echo "${{secrets.sf_known_hosts}}" > ~/.ssh/known_hosts
        # create gpg environment
        echo "Importing gpg key"
        echo "${{secrets.software_key}}" | gpg --batch --import
        echo "Listing gpg key"
        gpg --list-secret-keys --keyid-format LONG
        # create archive and transfer
        cd ~/stage
        tar cvfz $GITHUB_WORKSPACE/ezmlmn-obs.tar.gz *
        # create detached signature for obs archive
        echo "${{secrets.software_passphrase}}" | gpg2 --pinentry-mode loopback \
          --passphrase-fd 0 --default-key "${{secrets.software_user}}" \
          -o ezmlmn-obs.sig --detach-sig $GITHUB_WORKSPACE/ezmlmn-obs.tar.gz
        # copy to /home/frs/project/indimail
        scp -q -i ~/.private_key $GITHUB_WORKSPACE/ezmlmn-obs.tar.gz \
          ~/stage/ezmlmn-obs.sig "${{secrets.sf_user}}:${{secrets.sf_upload_path}}"
        rm -f ~/.private_key ~/.ssh/known_hosts $GITHUB_WORKSPACE/ezmlmn-obs.tar.gz
        rm -rf ~/stage
